| ddl_export                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| -- =====================================                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| -- СХЕМА БД FINTRACKAPP - ФАЗА 2 COMPLETED                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| -- Дата экспорта: 2025-08-03 18:45:56.937244+00                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| -- Включает: workspace management, приглашения, RLS политики                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| -- =====================================                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| -- ===== ПОЛЬЗОВАТЕЛЬСКИЕ ТИПЫ =====                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| CREATE TYPE workspace_role AS ENUM ('Owner', 'Admin', 'Member', 'Viewer');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| -- ===== СОЗДАНИЕ ТАБЛИЦ =====                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| CREATE TABLE workspace_invitations (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    workspace_id uuid NOT NULL,
    invited_by uuid NOT NULL,
    invited_email text NOT NULL,
    role text NOT NULL,
    status text DEFAULT 'pending'::text,
    invitation_token uuid NOT NULL DEFAULT gen_random_uuid(),
    invited_at timestamp without time zone DEFAULT now(),
    expires_at timestamp without time zone DEFAULT (now() + '7 days'::interval),
    accepted_at timestamp without time zone,
    declined_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
); |
| CREATE TABLE workspace_members (
    workspace_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role workspace_role NOT NULL DEFAULT 'Member'::workspace_role,
    invited_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    joined_at timestamp without time zone DEFAULT now(),
    last_accessed_at timestamp without time zone DEFAULT now(),
    is_active boolean DEFAULT true
);                                                                                                                                                                                                                                                          |
| CREATE TABLE workspaces (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    owner_id uuid NOT NULL,
    name text NOT NULL,
    is_personal boolean NOT NULL DEFAULT false,
    deleted_at timestamp with time zone
);                                                                                                                                                                                                                                                                                                                                                               |
| -- ===== ПЕРВИЧНЫЕ КЛЮЧИ =====                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| ALTER TABLE workspace_invitations ADD CONSTRAINT workspace_invitations_pkey PRIMARY KEY (id);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| ALTER TABLE workspace_members ADD CONSTRAINT workspace_members_pkey PRIMARY KEY (workspace_id, user_id);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| ALTER TABLE workspaces ADD CONSTRAINT workspaces_pkey PRIMARY KEY (id);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| -- ===== ВНЕШНИЕ КЛЮЧИ =====                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| ALTER TABLE workspace_invitations ADD CONSTRAINT workspace_invitations_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE ON UPDATE NO ACTION;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| ALTER TABLE workspace_members ADD CONSTRAINT workspace_members_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE ON UPDATE NO ACTION;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| -- ===== УНИКАЛЬНЫЕ ОГРАНИЧЕНИЯ =====                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| ALTER TABLE workspace_invitations ADD CONSTRAINT workspace_invitations_invitation_token_key UNIQUE (invitation_token);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| ALTER TABLE workspace_invitations ADD CONSTRAINT unique_workspace_email_pending UNIQUE (workspace_id, invited_email, status);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| -- ===== CHECK ОГРАНИЧЕНИЯ =====                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| ALTER TABLE workspace_invitations ADD CONSTRAINT valid_expiry CHECK (expires_at > invited_at);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| ALTER TABLE workspace_invitations ADD CONSTRAINT workspace_invitations_role_check CHECK (role = ANY (ARRAY['Owner'::text, 'Admin'::text, 'Member'::text, 'Viewer'::text, 'owner'::text, 'admin'::text, 'member'::text, 'viewer'::text]));                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| ALTER TABLE workspace_invitations ADD CONSTRAINT workspace_invitations_status_check CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text, 'expired'::text]));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| -- ===== ИНДЕКСЫ =====                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| CREATE INDEX idx_workspace_invitations_workspace ON public.workspace_invitations USING btree (workspace_id);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| CREATE INDEX idx_workspace_invitations_token ON public.workspace_invitations USING btree (invitation_token);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| CREATE INDEX idx_workspace_members_role ON public.workspace_members USING btree (workspace_id, role);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| CREATE INDEX idx_workspace_invitations_status ON public.workspace_invitations USING btree (status) WHERE (status = 'pending'::text);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| CREATE INDEX idx_workspace_members_workspace_user ON public.workspace_members USING btree (workspace_id, user_id);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| CREATE INDEX idx_workspace_members_user ON public.workspace_members USING btree (user_id) WHERE (is_active = true);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| CREATE INDEX idx_workspace_invitations_email ON public.workspace_invitations USING btree (invited_email);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| -- ===== ПОЛЬЗОВАТЕЛЬСКИЕ ФУНКЦИИ =====                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| CREATE OR REPLACE FUNCTION public.create_personal_workspace()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- Создаем персональное рабочее пространство
  INSERT INTO public.workspaces (owner_id, name, is_personal)
  VALUES (NEW.id, 'Personal', true);

  -- Добавляем пользователя в его новое персональное пространство как владельца
  INSERT INTO public.workspace_members (workspace_id, user_id, role)
  SELECT id, NEW.id, 'Owner' FROM public.workspaces WHERE owner_id = NEW.id AND is_personal = true;

  RETURN NEW;
END;
$function$
;                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| CREATE OR REPLACE FUNCTION public.expire_old_invitations()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
    UPDATE workspace_invitations 
    SET status = 'expired', updated_at = now()
    WHERE status = 'pending' 
      AND expires_at < now();
END;
$function$
;                                                                                                                                                                                                                                                                                                                                                                                          |
| CREATE OR REPLACE FUNCTION public.get_user_role_in_workspace(workspace_uuid uuid, user_uuid uuid)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    user_role TEXT;
BEGIN
    SELECT role::text INTO user_role
    FROM workspace_members
    WHERE workspace_id = workspace_uuid 
      AND user_id = user_uuid 
      AND is_active = true;
    
    RETURN COALESCE(normalize_role(user_role), 'none');
END;
$function$
;                                                                                                                                                                                                            |
| CREATE OR REPLACE FUNCTION public.normalize_role(input_role text)
 RETURNS text
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
BEGIN
    CASE LOWER(input_role)
        WHEN 'owner' THEN RETURN 'Owner';
        WHEN 'admin' THEN RETURN 'Admin';
        WHEN 'member' THEN RETURN 'Member';  
        WHEN 'viewer' THEN RETURN 'Viewer';
        ELSE RETURN input_role;
    END CASE;
END;
$function$
;                                                                                                                                                                                                                                                           |
| CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$function$
;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| CREATE OR REPLACE FUNCTION public.user_can_manage_workspace(workspace_uuid uuid, user_uuid uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    RETURN user_has_role(user_uuid, workspace_uuid, ARRAY['Owner', 'Admin']);
END;
$function$
;                                                                                                                                                                                                                                                                                                                                                                                                 |
| CREATE OR REPLACE FUNCTION public.user_has_role(user_uuid uuid, workspace_uuid uuid, required_roles text[])
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    user_role TEXT;
BEGIN
    SELECT role::text INTO user_role
    FROM workspace_members
    WHERE workspace_id = workspace_uuid 
      AND user_id = user_uuid 
      AND is_active = true;
    
    -- Нормализуем роль и проверяем
    RETURN normalize_role(user_role) = ANY(required_roles) OR LOWER(user_role) = ANY(ARRAY(SELECT LOWER(unnest(required_roles))));
END;
$function$
;                                                                               |
| -- ===== ТРИГГЕРЫ =====                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| CREATE TRIGGER update_workspace_invitations_updated_at BEFORE UPDATE ON public.workspace_invitations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| -- ===== ВКЛЮЧЕНИЕ ROW LEVEL SECURITY =====                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| ALTER TABLE workspace_invitations ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| ALTER TABLE workspace_members ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| -- ===== RLS ПОЛИТИКИ =====                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| CREATE POLICY "invitations_delete_policy" ON public.workspace_invitations AS PERMISSIVE FOR DELETE USING (((invited_by = auth.uid()) OR user_has_role(auth.uid(), workspace_id, ARRAY['Owner'::text])));                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| CREATE POLICY "invitations_insert_policy" ON public.workspace_invitations AS PERMISSIVE FOR INSERT WITH CHECK ((user_has_role(auth.uid(), workspace_id, ARRAY['Owner'::text, 'Admin'::text]) AND (invited_by = auth.uid())));                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| CREATE POLICY "invitations_select_policy" ON public.workspace_invitations AS PERMISSIVE FOR SELECT USING (((invited_by = auth.uid()) OR (invited_email = (( SELECT users.email
   FROM auth.users
  WHERE (users.id = auth.uid())))::text) OR user_has_role(auth.uid(), workspace_id, ARRAY['Owner'::text, 'Admin'::text])));                                                                                                                                                                                                                                                                                                                                                 |
| CREATE POLICY "invitations_update_policy" ON public.workspace_invitations AS PERMISSIVE FOR UPDATE USING (((invited_by = auth.uid()) OR ((invited_email = (( SELECT users.email
   FROM auth.users
  WHERE (users.id = auth.uid())))::text) AND (status = 'pending'::text))));                                                                                                                                                                                                                                                                                                                                                                                                |
| CREATE POLICY "workspace_members_delete_policy" ON public.workspace_members AS PERMISSIVE FOR UPDATE USING ((user_has_role(auth.uid(), workspace_id, ARRAY['Owner'::text]) OR ((user_id = auth.uid()) AND user_has_role(user_id, workspace_id, ARRAY['Member'::text, 'Viewer'::text]))));                                                                                                                                                                                                                                                                                                                                                                                     |
| CREATE POLICY "workspace_members_insert_policy" ON public.workspace_members AS PERMISSIVE FOR INSERT WITH CHECK (((user_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM workspace_invitations wi
  WHERE ((wi.workspace_id = workspace_members.workspace_id) AND (wi.invited_email = (( SELECT users.email
           FROM auth.users
          WHERE (users.id = auth.uid())))::text) AND (wi.status = 'pending'::text) AND (wi.expires_at > now()))))));                                                                                                                                                                                                                    |
| CREATE POLICY "workspace_members_select_policy" ON public.workspace_members AS PERMISSIVE FOR SELECT USING ((workspace_id IN ( SELECT wm.workspace_id
   FROM workspace_members wm
  WHERE ((wm.user_id = auth.uid()) AND (wm.is_active = true)))));                                                                                                                                                                                                                                                                                                                                                                                                                          |
| CREATE POLICY "workspace_members_update_policy" ON public.workspace_members AS PERMISSIVE FOR UPDATE USING ((user_has_role(auth.uid(), workspace_id, ARRAY['Owner'::text]) OR ((user_id = auth.uid()) AND (is_active = true))));                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| CREATE POLICY "workspaces_access_policy" ON public.workspaces AS PERMISSIVE FOR SELECT USING ((owner_id = auth.uid()));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| CREATE POLICY "workspaces_create_policy" ON public.workspaces AS PERMISSIVE FOR INSERT WITH CHECK ((auth.uid() = owner_id));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| CREATE POLICY "workspaces_delete_policy" ON public.workspaces AS PERMISSIVE FOR DELETE USING ((owner_id = auth.uid()));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| CREATE POLICY "workspaces_update_policy" ON public.workspaces AS PERMISSIVE FOR UPDATE USING ((owner_id = auth.uid())) WITH CHECK ((owner_id = auth.uid()));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| -- =====================================                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| -- КОНЕЦ ЭКСПОРТА СХЕМЫ БД                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| -- =====================================                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |